#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend luggard-alx-frontend
        bind *:80
        mode http
        default_backend luggard-alx-backend

backend luggard-alx-backend
        balance roundrobin
	server 17192-web-01 35.172.224.158:80 check
        server 17192-web-02 3.230.169.204:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 # enable haproxy to be started by init script

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
